services:
    app:
        build: .
        container_name: app
        networks:
            - insider
        entrypoint: >
            sh -c "
              ./.docker/wait-for-it.sh db:3306 --timeout=30 --strict -- echo 'DB ready!';
              php artisan migrate --force;
              php-fpm
            "
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: web
        ports:
            - "8080:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - insider
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: db
        environment:
            MYSQL_DATABASE: insider
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_HOST: '%'
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
        networks:
            - insider
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-psecret" ]
            interval: 5s
            timeout: 3s
            retries: 5

networks:
    insider:
        driver: bridge

volumes:
    dbdata:
