name: "Run Tests"
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
env:
  GITHUB_SHA_LONG: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref_name }}
  GH_RUN_ID: ${{ github.run_id }}

jobs:
  Testing:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull images
        run: docker compose pull

      - name: Build image and start compose
        run: docker compose up -d --build

      - name: Run tests
        run: docker compose exec app php artisan test

      - name: Stop compose
        run: docker compose down
